### ISSUE TITLE
Why is there a online icon on my pfp I'm at the home page

### ISSUE THREAD

**Issue by L22V31** [tersiswilvin/Roblox-Legacy-Old-Theme#84]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Chrome

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

Both

### Describe the Problem

<img width="919" alt="mamama" src="https://github.com/user-attachments/assets/d2877e6d-e5c1-4a8e-b59d-17b8392298d8">

**Comment by tersiswilvin** [comment]
Disable `avatarPresences` in Legacy Site Restoration.
![image](https://github.com/user-attachments/assets/01d874ea-8d4e-40b1-b367-a2635616a0ba)

**Comment by L22V31** [comment]
tysm

**Comment by tersiswilvin** [comment]
Your welcome!
